<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <ProjectReference Include="../../src/Atli.Reports.Aspire.Hosting.Azure/Atli.Reports.Aspire.Hosting.Azure.csproj" />
  </ItemGroup>
</Project>
