<Project Sdk="Aspire.AppHost.Sdk/13.6.0">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <ProjectReference
      Include="../../src/Atli.Reports.Aspire.Hosting.Azure/Atli.Reports.Aspire.Hosting.Azure.csproj"
      IsAspireProjectResource="false"
    />
  </ItemGroup>
</Project>
